In [1]:
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
import seaborn as sns

import pandas as pd

2024-04-11 14:47:44.304648: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-11 14:47:44.307449: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-11 14:47:44.352145: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-11 14:47:44.352973: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-11 14:47:45.101058: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [51]:
iris = datasets.load_iris()
print(iris.keys())
print(iris.target)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


**Question : analyser la structure des données. Combien d'échantillons ? Combien de paramètres ?**

In [52]:
print(iris.data.shape)
print(iris.feature_names)
print(iris.target_names)

(150, 4)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


Formattage des données

In [53]:
X = iris["data"][:, 0:4]
print(X)

# On créé une liste qui contient 1 lorsque la fleur est de type 2 et 0 sinon pour faire une classification
y = iris["target"]
print(y)

# Grâce à cette ligne, la classe 2 est étiquetée 1 et les classes 0 et 1 sont étiquetées 0
y = (iris["target"] == 2)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [54]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


Création du modèle

In [17]:

def my_model():
    model = Sequential()
    model.add(Dense(1, input_shape=(4,),activation='sigmoid'))
    return model
model = my_model()
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 5         
                                                                 
Total params: 5 (20.00 Byte)
Trainable params: 5 (20.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Initialisation des paraèmtres d'entraînnements

In [10]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Lancement de l'entraînnement

In [11]:
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
15/15 [==============================] - 0s 941us/step - loss: 2.4132 - accuracy: 0.6667
Epoch 2/150
15/15 [==============================] - 0s 933us/step - loss: 2.3323 - accuracy: 0.6667
Epoch 3/150
15/15 [==============================] - 0s 1ms/step - loss: 2.2471 - accuracy: 0.6667
Epoch 4/150
15/15 [==============================] - 0s 1ms/step - loss: 2.1698 - accuracy: 0.6667
Epoch 5/150
15/15 [==============================] - 0s 1ms/step - loss: 2.0878 - accuracy: 0.6667
Epoch 6/150
15/15 [==============================] - 0s 1ms/step - loss: 2.0057 - accuracy: 0.6667
Epoch 7/150
15/15 [==============================] - 0s 933us/step - loss: 1.9241 - accuracy: 0.6667
Epoch 8/150
15/15 [==============================] - 0s 1ms/step - loss: 1.8422 - accuracy: 0.6667
Epoch 9/150
15/15 [==============================] - 0s 1ms/step - loss: 1.7628 - accuracy: 0.6667
Epoch 10/150
15/15 [==============================] - 0s 1ms/step - loss: 1.6823 - accuracy: 0.6667
Epo

Evaluation des performances

In [16]:
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

5/5 [==============================] - 0s 3ms/step - loss: 0.1091 - accuracy: 0.9733
Accuracy: 97.33


**Question : exécuter l'apprentissage plusieurs fois et noter l'accuracy à chaque fois. Que constatez vous ?**

In [23]:
from tqdm import tqdm

perfs = []
for i in tqdm(range(10)):
    model = my_model()
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.fit(X, y, epochs=150, batch_size=10,verbose=0)
    _, accuracy = model.evaluate(X, y,verbose=0)
    perfs.append(accuracy)
    
print(perfs)

100%|██████████| 10/10 [00:37<00:00,  3.72s/it]

[0.95333331823349, 0.95333331823349, 0.9733333587646484, 0.9666666388511658, 0.9333333373069763, 0.9466666579246521, 0.9666666388511658, 0.9333333373069763, 0.8799999952316284, 0.7333333492279053]


Les résultats peuvent variés fortement d'un entraînement à un autre

In [ ]:
predictions = (model.predict(X) > 0.5).astype(int)
print(predictions)

**Question : modifier la structure du réseau en ajoutant une couche dense cachée de 2, 4, 8, 16 et 32 neurones. Utiliser la fonction d'activation Relu pour les couches cachées et sigmoid sur la dernière couche . Lancer à nouveau l'apprentissage.**

In [36]:
import time

def my_model():
    model = Sequential()
    model.add(Dense(2, input_shape=(4,),activation='relu'))
    model.add(Dense(4, input_shape=(2,),activation='relu'))
    model.add(Dense(8, input_shape=(4,),activation='relu'))
    model.add(Dense(16, input_shape=(8,),activation='relu'))
    model.add(Dense(32, input_shape=(16,),activation='relu'))
    model.add(Dense(1, input_shape=(32,),activation='sigmoid'))
    return model

model = my_model()
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
tic = time.time()
model.fit(X, y, epochs=150, batch_size=10,verbose=1)
tac = time.time()
print(f"time {tac-tic}")
_, accuracy = model.evaluate(X, y,verbose=1)
print("accuracy : {:.2f}".format(accuracy))

Epoch 1/150
15/15 [==============================] - 1s 3ms/step - loss: 0.7038 - accuracy: 0.6667
Epoch 2/150
15/15 [==============================] - 0s 4ms/step - loss: 0.6834 - accuracy: 0.6667
Epoch 3/150
15/15 [==============================] - 0s 2ms/step - loss: 0.6757 - accuracy: 0.6667
Epoch 4/150
15/15 [==============================] - 0s 2ms/step - loss: 0.6745 - accuracy: 0.6667
Epoch 5/150
15/15 [==============================] - 0s 2ms/step - loss: 0.6727 - accuracy: 0.6667
Epoch 6/150
15/15 [==============================] - 0s 3ms/step - loss: 0.6729 - accuracy: 0.6667
Epoch 7/150
15/15 [==============================] - 0s 3ms/step - loss: 0.6715 - accuracy: 0.6667
Epoch 8/150
15/15 [==============================] - 0s 3ms/step - loss: 0.6685 - accuracy: 0.6667
Epoch 9/150
15/15 [==============================] - 0s 2ms/step - loss: 0.6668 - accuracy: 0.6667
Epoch 10/150
15/15 [==============================] - 0s 2ms/step - loss: 0.6655 - accuracy: 0.6667
Epoch 11/

**Question : modifier la structure du réseau en ajoutant deux couches dense cachées de respectivement 32 et 64 neurones. Utiliser la fonction d'activation Relu pour les couches cachées et sigmoid sur la dernière couche . Lancer à nouveau l'apprentissage.**

In [35]:
import time

def my_model():
    model = Sequential()
    model.add(Dense(32, input_shape=(4,),activation='relu'))
    model.add(Dense(64, input_shape=(32,),activation='relu'))
    model.add(Dense(1, input_shape=(64,),activation='sigmoid'))
    return model

model = my_model()
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
tic = time.time()
model.fit(X, y, epochs=150, batch_size=10,verbose=1)
tac = time.time()
print(f"time {tac-tic}")
_, accuracy = model.evaluate(X, y,verbose=1)
print("accuracy : {:.2f}".format(accuracy))

Epoch 1/150
15/15 [==============================] - 1s 2ms/step - loss: 0.6742 - accuracy: 0.6667
Epoch 2/150
15/15 [==============================] - 0s 2ms/step - loss: 0.5848 - accuracy: 0.6667
Epoch 3/150
15/15 [==============================] - 0s 2ms/step - loss: 0.5316 - accuracy: 0.6800
Epoch 4/150
15/15 [==============================] - 0s 2ms/step - loss: 0.4865 - accuracy: 0.7600
Epoch 5/150
15/15 [==============================] - 0s 2ms/step - loss: 0.4433 - accuracy: 0.9067
Epoch 6/150
15/15 [==============================] - 0s 2ms/step - loss: 0.4084 - accuracy: 0.9533
Epoch 7/150
15/15 [==============================] - 0s 2ms/step - loss: 0.3746 - accuracy: 0.9600
Epoch 8/150
15/15 [==============================] - 0s 2ms/step - loss: 0.3493 - accuracy: 0.9667
Epoch 9/150
15/15 [==============================] - 0s 2ms/step - loss: 0.3296 - accuracy: 0.9733
Epoch 10/150
15/15 [==============================] - 0s 2ms/step - loss: 0.3115 - accuracy: 0.9667
Epoch 11/

**Question : que constater vous sur la durée de l'apprentissage, sur la valeur de loss et sur l'accuracy en opérant toutes les combinaisons relatives aux questions précédentes?**

Performance more stable on bigger and/or deeper models. Few layers with a lot of neurons perform about as fast as deep models with multiple layers and few neurons

# Diabetes dataset

In [44]:
dataset = loadtxt('dataset_diabetes.csv', delimiter=',')
print(dataset.shape)

(768, 9)


In [58]:
x = dataset[:,:-1]
y = dataset[:,-1:].reshape(-1)

In [62]:
x.shape

(768, 8)

In [68]:
def my_model():
    model = Sequential()
    model.add(Dense(32, input_shape=(8,),activation='relu'))
    model.add(Dense(64, input_shape=(32,),activation='relu'))
    model.add(Dense(1, input_shape=(64,),activation='sigmoid'))
    return model

In [69]:
model = my_model()
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
tic = time.time()
model.fit(x, y, epochs=150, batch_size=10,verbose=1)
tac = time.time()
print(f"time {tac-tic}")
_, accuracy = model.evaluate(x, y,verbose=1)
print("accuracy : {:.2f}".format(accuracy))

Epoch 1/150
77/77 [==============================] - 1s 4ms/step - loss: 1.9838 - accuracy: 0.5625
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 1.1151 - accuracy: 0.5820
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7952 - accuracy: 0.6263
Epoch 4/150
77/77 [==============================] - 0s 3ms/step - loss: 0.7874 - accuracy: 0.6536
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8364 - accuracy: 0.6237
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.9897 - accuracy: 0.6549
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7466 - accuracy: 0.6484
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6197 - accuracy: 0.6888
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6729 - accuracy: 0.6979
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7271 - accuracy: 0.6797
Epoch 11/